### ISSUE TITLE
Code examples in step 2.4 do not compile

### ISSUE THREAD

**Issue by PalaBeaveR** [rust-lang-ua/rustcamp#43]
## Summary
[This code example](https://github.com/rust-lang-ua/rust_incubator/blob/9856d7bde7fbaa4ad6bf3bdc9cd464bc02c992a9/2_idioms/2_4_generic_in_type_out/README.md?plain=1#L14-L40)  produces compiler errors because it cannot find the `AsRef` and `AsMut` derive macros since they are not available in the standard library and are instead provided by the [`derive_more`](https://docs.rs/derive_more/latest/derive_more/) crate.

In [this code example](https://github.com/rust-lang-ua/rust_incubator/blob/9856d7bde7fbaa4ad6bf3bdc9cd464bc02c992a9/2_idioms/2_4_generic_in_type_out/README.md?plain=1#L42-L63) the compiler complains about [not being able to mutate immutable variable `v`](https://github.com/rust-lang-ua/rust_incubator/blob/9856d7bde7fbaa4ad6bf3bdc9cd464bc02c992a9/2_idioms/2_4_generic_in_type_out/README.md?plain=1#L49), the [`Nickname` struct definition](https://github.com/rust-lang-ua/rust_incubator/blob/9856d7bde7fbaa4ad6bf3bdc9cd464bc02c992a9/2_idioms/2_4_generic_in_type_out/README.md?plain=1#L52-L56) is missing and, even with `derive_more` crate in the project, the `AsRef<str>` trait is not implemented on `Nickname`. The `AsRef` derive macro instead generates the `AsRef<String>` implementation. 

## Possible fixes
- `derive_more` crate should be mentioned.
```rust
use derive_more::{AsMut, AsRef};
```
- The use statement above should be added to both examples.
- The `Nickname` struct definition should be added to the second example.
- `add_hi` function should have a `mut` keyword added to the `v` argument in the second example.
- `just_print_stringy` should have the `AsRef<str>` trait bound changed to `AsRef<String>` in the second example.

**Comment by SupperZum** [comment]
Thank you! Fixed)
