### ISSUE TITLE
Add section for idiomatic error handling using external crates

### ISSUE THREAD

**Issue by mhnap** [rust-lang-ua/rustcamp#46]
## Problem to solve
I think there is a gap in learning materials for studying how to idiomatically use error handling with crates in Rust.

## Proposal
Add one more section with a task (possibly in the 3_ecosystem chapter) for learning error handling with crates (thiserror, anyhow, etc.).   
It is just a brief small idea, but we also can add more related information to this section (different panic handling and maybe some other crates, etc.)

## Links & references
Some of the possible provided links for learning materials:
https://blog.yoshuawuyts.com/error-handling-survey/
https://www.shakacode.com/blog/thiserror-anyhow-or-how-i-handle-errors-in-rust-apps/
https://antoinerr.github.io/blog-website/2023/01/28/rust-anyhow.html
https://nick.groenen.me/posts/rust-error-handling/
https://www.shuttle.rs/blog/2022/06/30/error-handling

**Comment by SupperZum** [comment]
Thank you for the idea
