### ISSUE TITLE
Backtick used instead of apostrophe

### ISSUE THREAD

**Issue by vladislav-tkach** [rust-lang-ua/rustcamp#54]
Caused by ad470e224995060796f7d1bb53ac6d5e13d51a2e

## Summary

A backtick is used in "don`t" instead of an apostrophe as in "don't."

**Comment by vladislav-tkach** [comment]
Caused by: 88187e8f102db11bcea9d8eb555e159ffaa79698

Another appearance in `/faq.md`

**Comment by SupperZum** [comment]
Thanks 👍
