### ISSUE TITLE
PR title convention ambiguity

### ISSUE THREAD

**Issue by Fourier2718281828** [rust-lang-ua/rustcamp#58]
Caused by [commit](https://github.com/rust-lang-ua/rustcamp/commit/89c00855036656990ad055cac3f98beec93a2d8a#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R10)

## Summary
When creating a PR the description default template suggests naming PRs as follows: `Step <step-number>: <step-name>`. That seems to be an outdated convention.

## What is the expected _correct_ behavior?
According to `faq.md` the relevant name for a PR is `task_task_number`. So please correct the [description template](https://github.com/rust-lang-ua/rustcamp/blob/master/.github/PULL_REQUEST_TEMPLATE.md) so that it meets the convention stated in `faq.md`.

**Comment by SupperZum** [comment]
Thanks 👍
