### ISSUE TITLE
How to join the course

### ISSUE THREAD

**Issue by ribery77** [rust-lang-ua/rustcamp#63]
Hi all,

I am unable to get from the bot invitation to join course. Would you like to help me please?
Thanks in advance.

**Comment by NamesMark** [comment]
The registration for "Rust Bootcamp — Winter 2023-2024" ended on December 14th. This bootcamp is organized by the Rust Ukraine community, a member of which you can become by joining the [public Tg chat](https://t.me/rustlang_ua)! (but be aware that it is only in Ukrainian) All the information about the future bootcamps is always posted and discussed there.

Alternatively, nothing stops you from forking this repository and solving the tasks on your owd, and I'm sure you can find some people to help you or review the code.
