### ISSUE TITLE
inaccuracy in the task 3_10_threads 

### ISSUE THREAD

**Issue by 01110000u01101110k** [rust-lang-ua/rustcamp#69]
## Summary

It seems that in the table "Multiprocessing vs Multithreading", in the row "Pickling objects", the elements are mixed up.

"Multithreading avoids pickling." in the "Multiprocessing" column.

"Multiprocessing relies on pickling objects in memory to send to other processes." in the "Multithreading" column.

**Comment by TheBestTvarynka** [comment]
fixed in #76
